import { useEffect, useState } from 'react';
import { FiActivity, FiBell, FiRefreshCw, FiUsers, FiClock, FiChevronRight } from 'react-icons/fi';

const API_BASE = (import.meta.env.VITE_API_BASE_URL || '').replace(/\/$/, '');

export default function DoctorPage() {
  const [alerts, setAlerts] = useState([]); const [submissions, setSubmissions] = useState([]); const [loading, setLoading] = useState(true);
  const loadData = () => { setLoading(true); Promise.all([fetch(`${API_BASE}/api/sos`).then(r => r.json()), fetch(`${API_BASE}/api/doctor/queue`).then(r => r.json())]).then(([sos, queue]) => { setAlerts(sos.alerts || []); setSubmissions(queue.submissions || []); }).catch(() => { setAlerts([]); setSubmissions([]); }).finally(() => setLoading(false)); };
  useEffect(() => { loadData(); }, []);
  return <div className="min-h-screen bg-[#f6f8fb] p-5 sm:p-8 text-[#1A1A2E] relative overflow-hidden"><div className="absolute -right-32 -top-32 w-96 h-96 rounded-full bg-[#c8ebf6] blur-3xl opacity-60" /><div className="relative max-w-6xl mx-auto">
    <header className="flex flex-col sm:flex-row sm:items-center justify-between gap-5 mb-8 animate-float-in"><div><div className="flex items-center gap-3 text-[#0F4C75]"><div className="w-12 h-12 rounded-2xl bg-[#0F4C75] text-white flex items-center justify-center shadow-lg"><FiActivity size={27}/></div><div><p className="text-xs uppercase tracking-[.25em] font-bold text-[#5b8da5]">Clinical workspace</p><h1 className="text-3xl sm:text-4xl font-bold tracking-tight">Doctor Portal</h1></div></div><p className="text-gray-600 mt-3 text-lg">A focused view of patients who need attention.</p></div><button onClick={loadData} className="self-start flex items-center gap-2 px-5 py-3 bg-white rounded-2xl shadow border border-white font-semibold hover:-translate-y-1 transition-transform"><FiRefreshCw className={loading ? 'animate-spin' : ''}/> Refresh</button></header>
    <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-7"><Stat icon={<FiBell/>} label="SOS alerts" value={alerts.length} tone="red"/><Stat icon={<FiUsers/>} label="Intake queue" value={submissions.length} tone="blue"/><Stat icon={<FiClock/>} label="Status" value="Live" tone="green"/></div>
    <section className="glass-panel rounded-3xl p-5 sm:p-8 animate-float-in" style={{animationDelay:'120ms'}}><div className="flex items-center gap-3 mb-6"><FiBell className="text-[#E63946]" size={25}/><div><h2 className="text-2xl font-bold">Emergency alerts</h2><p className="text-gray-500">SOS notifications from the kiosk</p></div><span className="ml-auto rounded-full bg-red-100 text-red-700 px-3 py-1 font-bold">{alerts.length} active</span></div>{loading ? <p className="py-8 text-gray-500">Loading live data...</p> : alerts.length === 0 ? <div className="py-10 text-center bg-[#f7fafc] rounded-2xl"><div className="mx-auto w-12 h-12 rounded-full bg-emerald-100 text-emerald-600 flex items-center justify-center mb-3">✓</div><p className="font-semibold">No emergency alerts right now</p><p className="text-gray-500 mt-1">This panel will update after a patient presses SOS.</p></div> : <div className="space-y-3">{alerts.map(alert => <article key={alert.id} className="border border-red-100 border-l-4 border-l-[#E63946] bg-red-50/80 rounded-2xl p-5"><div className="flex justify-between gap-3"><strong className="text-red-900">Emergency SOS</strong><span className="text-sm text-red-700">{new Date(alert.created_at).toLocaleString()}</span></div><p className="mt-2 text-red-900/80">Token: {alert.token || 'Unidentified patient'} · Language: {alert.language || 'en'}</p></article>)}</div>}</section>
    <section className="mt-6 bg-white rounded-3xl p-5 sm:p-8 shadow-[0_12px_40px_rgba(15,76,117,.07)] animate-float-in" style={{animationDelay:'220ms'}}><div className="flex items-center justify-between mb-5"><div><h2 className="text-2xl font-bold">Patient intake queue</h2><p className="text-gray-500">Essential clinical details only</p></div><FiChevronRight className="text-gray-400"/></div>{submissions.length === 0 ? <p className="py-6 text-gray-500">No patient submissions yet.</p> : <div className="space-y-3">{submissions.map(item => <article key={item.id} className="rounded-2xl bg-[#f8fbfd] border border-[#e4eef3] p-4"><div className="flex flex-wrap justify-between gap-2"><strong>Token {item.token}</strong><span className="text-sm text-gray-500">{new Date(item.created_at).toLocaleString()}</span></div><p className="mt-2 font-medium">{item.doctor_summary?.chief_complaint || item.history?.complaint || 'No complaint recorded'}</p><p className="text-sm text-gray-500 mt-1">{item.doctor_summary?.symptoms?.join(', ') || 'Symptoms not selected'} · {item.language || 'en'}</p></article>)}</div>}</section>
  </div></div>;
}

function Stat({ icon, label, value, tone }) { const colors = { red: 'bg-red-50 text-red-600', blue: 'bg-blue-50 text-[#0F4C75]', green: 'bg-emerald-50 text-emerald-600' }; return <div className="bg-white rounded-2xl p-5 shadow-[0_10px_30px_rgba(15,76,117,.06)] flex items-center gap-4"><div className={`w-11 h-11 rounded-xl flex items-center justify-center ${colors[tone]}`}>{icon}</div><div><p className="text-sm text-gray-500">{label}</p><p className="text-2xl font-bold">{value}</p></div></div>; }
